name = "kai981-km-bot"
main = "src/worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

[triggers]
crons = ["*/5 * * * *"]

[vars]
PUBLIC_ORIGIN = "https://c04u41125.github.io"

[[d1_databases]]
binding = "DB"
database_name = "kai981-km"
database_id = "42b1967c-9b52-4fc2-ad4e-e39246f1a93b"
migrations_dir = "migrations"
